version: '3.8'

services:
  sal0-legendas:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: ghcr.io/sal0-apps/sal0-legendas:latest
    container_name: sal0-legendas-app
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Sao_Paulo
      - PYTHONUNBUFFERED=1
